# Infrastructure pipeline

# This pipeline deploys a vnet, subnet, nsg and storage account as infrastructure as part of an sample workload

trigger:
- master

resources:
- repo: self

variables:
  azureSubscription: 'netcoreconf2020'

pool:  
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build_Linux_Ubuntu
    displayName: Deploy Infrastrucure Resources
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: Create ACR
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'create-acr.sh'
        addSpnToEnvironment: true
    - task: AzureCLI@2
      displayName: Create VNet, SubsNet and NSG
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'create-vnet.sh'
        addSpnToEnvironment: true
    - task: AzureCLI@2
      displayName: Create Storage Account
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'create-storage.sh'
        addSpnToEnvironment: true
